//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MvcApplication1.Models
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class starwarsTOREntities2 : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet starwarsTOREntities2 à l'aide de la chaîne de connexion trouvée dans la section 'starwarsTOREntities2' du fichier de configuration d'application.
        /// </summary>
        public starwarsTOREntities2() : base("name=starwarsTOREntities2", "starwarsTOREntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet starwarsTOREntities2.
        /// </summary>
        public starwarsTOREntities2(string connectionString) : base(connectionString, "starwarsTOREntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet starwarsTOREntities2.
        /// </summary>
        public starwarsTOREntities2(EntityConnection connection) : base(connection, "starwarsTOREntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<classes> classes
        {
            get
            {
                if ((_classes == null))
                {
                    _classes = base.CreateObjectSet<classes>("classes");
                }
                return _classes;
            }
        }
        private ObjectSet<classes> _classes;

        #endregion
        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet classes. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToclasses(classes classes)
        {
            base.AddObject("classes", classes);
        }

        #endregion
    }
    

    #endregion
    
    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="starwarsTORModel", Name="classes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class classes : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet classes.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        public static classes Createclasses(global::System.Int32 id)
        {
            classes classes = new classes();
            classes.id = id;
            return classes;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String titre
        {
            get
            {
                return _titre;
            }
            set
            {
                OntitreChanging(value);
                ReportPropertyChanging("titre");
                _titre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("titre");
                OntitreChanged();
            }
        }
        private global::System.String _titre;
        partial void OntitreChanging(global::System.String value);
        partial void OntitreChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Identification
        {
            get
            {
                return _Identification;
            }
            set
            {
                OnIdentificationChanging(value);
                ReportPropertyChanging("Identification");
                _Identification = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Identification");
                OnIdentificationChanged();
            }
        }
        private global::System.String _Identification;
        partial void OnIdentificationChanging(global::System.String value);
        partial void OnIdentificationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Equipement
        {
            get
            {
                return _Equipement;
            }
            set
            {
                OnEquipementChanging(value);
                ReportPropertyChanging("Equipement");
                _Equipement = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Equipement");
                OnEquipementChanged();
            }
        }
        private global::System.String _Equipement;
        partial void OnEquipementChanging(global::System.String value);
        partial void OnEquipementChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TactiqueCombat
        {
            get
            {
                return _TactiqueCombat;
            }
            set
            {
                OnTactiqueCombatChanging(value);
                ReportPropertyChanging("TactiqueCombat");
                _TactiqueCombat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TactiqueCombat");
                OnTactiqueCombatChanged();
            }
        }
        private global::System.String _TactiqueCombat;
        partial void OnTactiqueCombatChanging(global::System.String value);
        partial void OnTactiqueCombatChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Partenaire
        {
            get
            {
                return _Partenaire;
            }
            set
            {
                OnPartenaireChanging(value);
                ReportPropertyChanging("Partenaire");
                _Partenaire = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Partenaire");
                OnPartenaireChanged();
            }
        }
        private global::System.String _Partenaire;
        partial void OnPartenaireChanging(global::System.String value);
        partial void OnPartenaireChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VaisseauxId
        {
            get
            {
                return _VaisseauxId;
            }
            set
            {
                OnVaisseauxIdChanging(value);
                ReportPropertyChanging("VaisseauxId");
                _VaisseauxId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VaisseauxId");
                OnVaisseauxIdChanged();
            }
        }
        private Nullable<global::System.Int32> _VaisseauxId;
        partial void OnVaisseauxIdChanging(Nullable<global::System.Int32> value);
        partial void OnVaisseauxIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AffiliationId
        {
            get
            {
                return _AffiliationId;
            }
            set
            {
                OnAffiliationIdChanging(value);
                ReportPropertyChanging("AffiliationId");
                _AffiliationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AffiliationId");
                OnAffiliationIdChanged();
            }
        }
        private Nullable<global::System.Int32> _AffiliationId;
        partial void OnAffiliationIdChanging(Nullable<global::System.Int32> value);
        partial void OnAffiliationIdChanged();

        #endregion
    
    }

    #endregion
    
}
